CREATE database proyecto2;
use proyecto2;

SET GLOBAL local_infile=1;
SHOW GLOBAL VARIABLES LIKE 'local_infile';
LOAD DATA LOCAL INFILE 'C:\\Users\\crisg\\Documents\\GitHub\\bd1-proyecto2-201801480\\data.csv' 
INTO TABLE proyecto2.TEMPORARY COLUMNS TERMINATED BY ','
LINES TERMINATED BY '\r\n' -- LINUX  '\n' 
IGNORE 1 LINES (NOMBRE_ELECCION,AÑO_ELECCION,PAIS,REGION,DEPTO,MUNICIPIO,PARTIDO,NOMBRE_PARTIDO,SEXO,RAZA,ANALFABETOS,ALFABETOS,SEXO,RAZA,PRIMARIA,NIVEL_MEDIO,UNIVERSITARIOS);


CREATE TABLE TEMPORARY (
    NOMBRE_ELECCION VARCHAR(100),
    AÑO_ELECCION VARCHAR(100),
    PAIS VARCHAR(100),
    REGION VARCHAR(100),
    DEPTO VARCHAR(100),
    MUNICIPIO VARCHAR(100),
    PARTIDO VARCHAR(100),
    NOMBRE_PARTIDO VARCHAR(100),
    SEXO VARCHAR(100),
    RAZA VARCHAR(100),
    ANALFABETOS VARCHAR(100),
    ALFABETOS VARCHAR(100),
    -- SEXO VARCHAR(100),
    -- RAZA VARCHAR(100),
    PRIMARIA VARCHAR(100),
    NIVEL_MEDIO VARCHAR(100),
    UNIVERSITARIOS VARCHAR(100)
);


SELECT COUNT(*) FROM TEMPORARY;